### ISSUE TITLE
upload newest version to Pypi

### ISSUE THREAD

**Issue by wilberth** [xypron/pysispm#2]
Would be nice if you could upload the newest version (that includes idProduct=0xfd15) to the python package index.

**Comment by xypron** [comment]
@wilberth  Kindly test version 0.6 from Pypi.

**Comment by wilberth** [comment]
sispmctl.py works as expected (channels can be switched on and off) with my energenie eg-pm2 identifying as 04b4:fd15 
- on ubuntu 18.04 with python 3.6 and
- when adding 'from __future__ import print_function' also with python 2.7.
- querying the status works on windows 7 with python 2.7, setting relays on and off does not (errno 5, ioerror)

**Comment by xypron** [comment]
Python 2 is not supported by pysispm. Anyway Python 2 is close to end of life.
