### ISSUE TITLE
usb.core.USBError: [Errno 32] Pipe error

### ISSUE THREAD

**Issue by xypron** [xypron/pysispm#5]
@robho: wrote in pull request #4 

I haven't thought much about the delay.

I now tried setting the delay to 1 ms and ran a few tests. Most of the time one (1) retry is enough, but I've seen two retries (2 ms delay in total) needed a few times. So, 1 ms delay and 2 or 3 tries should be enough for me to get stable results.

Would you like to keep the behaviour close to that of sispmctl and let the delay depend on the loop iteration?

I've also seen this error, but I haven't done anything about it:
```
  File "/home/robert/.local/lib/python3.5/site-packages/sispm/__init__.py", line 164, in switchoff
    _send_ctrl_transfer(dev, 0x21, 0x09, 0x0300 + 3 * i, 0, buf, 500)
  File "/home/robert/.local/lib/python3.5/site-packages/sispm/__init__.py", line 65, in _send_ctrl_transfer
    wIndex, data_or_wLength, timeout)
  File "/home/robert/.local/lib/python3.5/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/robert/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/home/robert/.local/lib/python3.5/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

It happens more seldom than the "no data" error that the retry loop handles, but it's relatively easy to reproduce for me. I've only seen it with switchoff()/switchon(), not getstatus().

Maybe we should retry usb commands for this error also? Any thoughts?

**Comment by xypron** [comment]
usb.core.USBError: [Errno 32] Pipe error indicates that the USB device is in use.

**Comment by xypron** [comment]
On 9/19/19 7:05 PM, Robert Högberg @robho  wrote:
> I'm running this program:
> 
> |import sispm import time devices = sispm.connect() while True: 
> time.sleep(0.5) sispm.getid(devices[0]) sispm.getstatus(devices[0], 1) 
> sispm.switchon(devices[0], 2) |
> 
> The program can run fine for a few minutes, then the pipe error appears. 
> That shouldn't happen, right?
> 
> If you have made changes to branch dispose_resources, you need to push 
> them, then I'll run tests.
> 
> (I doubt disposing the resources will help though. I've been using 
> https://github.com/jerch/python-sispm before and it disposes the 
> resources after use, but I'm seeing problems there also.)
> 
> I'll run some more tests and provide more information.
> 

I can reproduce this error occuring in getid() on my system. This is the relevant libusb debug output:

```
libusb: debug [reap_for_handle] urb type=2 status=-71 transferred=0
libusb: debug [handle_control_completion] handling completion status -71
libusb: debug [handle_control_completion] low-level bus error occurred
```
In Linux's errno.h I find:

`#define EPROTO          71      /* Protocol error */`

In this case retrying seems to be the only plausible solution.

**Comment by xypron** [comment]
Pushed 11d9cecce023 ("Retry on usb.core.USBError")

@robho Does this solve the problem for you?

**Comment by robho** [comment]
Yes, 11d9cec fixes the pipe errors for me.

I see that you skipped a delay when retrying after the USBError. I tried to remove the delay for the "no data" situation and it looks like there's no need for the delay; I don't get more retries when the delay is removed. If you feel like it I think the delay I added can be removed.

Thanks for your help with this! :+1:

**Comment by xypron** [comment]
@robho 

Thanks for testing. I have removed the wait now.

I guess when we get a failure 5 consecutive times we should throw an error. Otherwise the calling software cannot react to the defect.

**Comment by robho** [comment]
Sounds like a good idea to propagate the error to the caller when retrying fails.
